# Generated by Django 6.0.7 on 2026-07-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paymet_data', models.DateField()),
                ('for_month', models.CharField(max_length=100)),
                ('paymet_tayp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10000)),
                ('role', models.CharField(choices=[('ceo', 'Ceo'), ('teacher', 'Teacher'), ('student', 'Student'), ('user', 'User')], default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.DateField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_data', models.DateField()),
                ('for_month', models.CharField(max_length=100)),
                ('salary_type', models.CharField(max_length=100)),
                ('paymet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.paymet')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.user')),
            ],
        ),
        migrations.AddField(
            model_name='paymet',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.user'),
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.group')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('none', 'None')], default='none', max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.group')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceo.user')),
            ],
        ),
    ]
