# Generated by Django 6.0.7 on 2026-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='groups',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
