# Generated by Django 6.0.7 on 2026-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_created_at_alter_groups_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
