# Generated by Django 6.0.7 on 2026-07-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupstudent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
